apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameserver-deployment
  template:
    metadata:
      labels:
        app: gameserver-deployment
    spec:
      containers:
        - name: gameserver-deployment
          image: joohuba/huba-game-server:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "125m"
          ports:
            - containerPort: 8090
          env:
            - name: DB_HOST
              value: "postgres"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: LOADBALANCER_IP
              valueFrom:
                configMapKeyRef:
                  name: gameserver-config
                  key: LOADBALANCER_IP
